option(JuceModule_Analytics "Juce analytics module" ON)
option(JuceModule_AudioBasics "Juce audio basics module" ON)
option(JuceModule_AudioDevices "Juce audio devices module" ON)
option(JuceModule_AudioFormats "Juce audio formats module" ON)
option(JuceModule_AudioProcessors "Juce audio processors module" ON)
option(JuceModule_AudioUtils "Juce audio utils module" ON)
option(JuceModule_BlocksBasics "Juce blocks basics module" ON)
option(JuceModule_Box2d "Juce box2d module" ON)
option(JuceModule_Core "Juce core module" ON)
option(JuceModule_Cryptography "Juce cryptography module" ON)
option(JuceModule_DataStructures "Juce data structures module" ON)
option(JuceModule_DSP "Juce DSP module" ON)
option(JuceModule_Events "Juce events module" ON)
option(JuceModule_GUIBasics "Juce GUI basics module" ON)
option(JuceModule_Graphics "Juce graphics module" ON)
option(JuceModule_GUIExtra "Juce GUI extra module" ON)
option(JuceModule_OpenGL "Juce OpenGL module" ON)
option(JuceModule_OSC "Juce OSC module" ON)
option(JuceModule_ProductUnlocking "Juce product unlocking module" ON)
option(JuceModule_Video "Juce product video module" ON)

function(juce_source SOURCE)
    list(APPEND juce_SOURCES ${SOURCE})
    set(juce_SOURCES ${juce_SOURCES} PARENT_SCOPE)
endfunction(juce_source)

juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/AppConfig.h)
juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/JuceHeader.h)

if(JuceModule_Analytics)
    juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_analytics.cpp)
endif(JuceModule_Analytics)

if(JuceModule_AudioBasics)
    if(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_audio_basics.mm)
    else(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_audio_basics.cpp)
    endif(APPLE)
endif(JuceModule_AudioBasics)

if(JuceModule_AudioDevices)
    if(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_audio_devices.mm)
    else(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_audio_devices.cpp)
    endif(APPLE)
endif(JuceModule_AudioDevices)

if(JuceModule_AudioFormats)
    if(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_audio_formats.mm)
    else(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_audio_formats.cpp)
    endif(APPLE)
endif(JuceModule_AudioFormats)

if(JuceModule_AudioProcessors)
    if(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_audio_processors.mm)
    else(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_audio_processors.cpp)
    endif(APPLE)
endif(JuceModule_AudioProcessors)

if(JuceModule_AudioUtils)
    if(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_audio_utils.mm)
    else(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_audio_utils.cpp)
    endif(APPLE)
endif(JuceModule_AudioUtils)

if(JuceModule_BlocksBasics)
    juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_blocks_basics.cpp)
endif(JuceModule_BlocksBasics)

if(JuceModule_Box2d)
    juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_box2d.cpp)
endif(JuceModule_Box2d)

if(JuceModule_Core)
    if(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_core.mm)
    else(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_core.cpp)
    endif(APPLE)
endif(JuceModule_Core)

if(JuceModule_Cryptography)
    if(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_cryptography.mm)
    else(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_cryptography.cpp)
    endif(APPLE)
endif(JuceModule_Cryptography)

if(JuceModule_DataStructures)
    if(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_data_structures.mm)
    else(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_data_structures.cpp)
    endif(APPLE)
endif(JuceModule_DataStructures)

if(JuceModule_DSP)
    if(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_dsp.mm)
    else(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_dsp.cpp)
    endif(APPLE)
endif(JuceModule_DSP)

if(JuceModule_Events)
    if(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_events.mm)
    else(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_events.cpp)
    endif(APPLE)
endif(JuceModule_Events)

if(JuceModule_GUIBasics)
    if(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_gui_basics.mm)
    else(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_gui_basics.cpp)
    endif(APPLE)
endif(JuceModule_GUIBasics)

if(JuceModule_Graphics)
    if(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_graphics.mm)
    else(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_graphics.cpp)
    endif(APPLE)
endif(JuceModule_Graphics)

if(JuceModule_GUIExtra)
    if(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_gui_extra.mm)
    else(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_gui_extra.cpp)
    endif(APPLE)
endif(JuceModule_GUIExtra)

if(JuceModule_OpenGL)
    if(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_opengl.mm)
    else(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_opengl.cpp)
    endif(APPLE)
endif(JuceModule_OpenGL)

if(JuceModule_OSC)
    juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_osc.cpp)
endif(JuceModule_OSC)

if(JuceModule_ProductUnlocking)
    if(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_product_unlocking.mm)
    else(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_product_unlocking.cpp)
    endif(APPLE)
endif(JuceModule_ProductUnlocking)

if(JuceModule_Video)
    if(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_video.mm)
    else(APPLE)
        juce_source(${CMAKE_CURRENT_LIST_DIR}/JuceLibraryCode/include_juce_video.cpp)
    endif(APPLE)
endif(JuceModule_Video)

